replicaCount: 3

image:
  repository: devops-app
  tag: lab13-local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

app:
  environment: blue-v1

persistence:
  enabled: false

rollout:
  enabled: true
  strategy: blueGreen
  blueGreen:
    activeServiceSuffix: active
    previewServiceSuffix: preview
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
