---
web_app_name: devops-python
web_app_docker_image: "{{ dockerhub_username }}/devops-app"
web_app_docker_image_tag: latest
web_app_port: 5000
web_app_internal_port: 5000
web_app_compose_project_dir: "/opt/{{ web_app_name }}"
